/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Medal } from './medal';
import { Section } from './section';

export interface Race {
    id: number;
    dateAvailability?: string;
    name: string;
    laps?: number;
    difficulty?: number;
    image?: string;
    optional?: boolean;
    nextRace?: number;
    previousRace?: number;
    sections?: Array<Section>;
    medals?: Array<Medal>;
}
