/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Race } from './race';
import { Team } from './team';
import { Vehicle } from './vehicle';

export interface RunResult { 
    time?: number;
    date?: string;
    medal?: string;
    team?: Team;
    race?: Race;
    rank?: number;
    wearByLaps?: number;
    consumptionByLaps?: number;
    stats?: Vehicle;
}