/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';
import { Team } from './team';

export interface TransactionResponse { 
    price?: number;
    status?: string;
    creationDate?: Date;
    completionDate?: Date;
    openingDate?: Date;
    item?: Item;
    teamSeller?: Team;
    teamBuyer?: Team;
    id?: number;
}